### ISSUE TITLE
React 기본 레이아웃 세팅

### ISSUE THREAD

**Issue by jspark2000** [y-jiu/cnc-dashboard#1]
### Tasks

- [ ] React Router 적용
- [ ] 기본 컴포넌트 만들기
- [ ] css 프레임워크 변경(styled-component -> tailwindcss)
- [ ] 프로젝트 구조 변경
